### ISSUE TITLE
incompatible with MMM-Remote-Control

### ISSUE THREAD

**Issue by ihadx** [choffmann/MMM-YT-SubCount#1]
When MMM-YT-SubCount is enabled I can no longer show/hide modules using the very useful Jopyth/MMM-Remote-Control module. Disabling YT-SubCount fixed the issue.
Steps to replicate:
1) install and enable both MMM-YT-SubCount and MMM-Remote-Control
2) go to http://magicmirroriphere:8080/remote.html
3) Click on 'Edit View' button
4) See error message

**Comment by choffmann** [comment]
Thanks for your description. I will look at this issue when I find some time.

**Comment by choffmann** [comment]
I have found the problem, you should be able to use the MMM-Remote-Control module with the MMM-YT-SubCount module now
